In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('CC_Data.csv', sep = ',', header = 0)

In [3]:
df.head()

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0     -2  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  Default  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  

[5 rows x 24 columns]

In [4]:
X = df.values[:,0:23]
Y = df.values[:,23]

In [5]:
X

array([[ 20000,      2,      2, ...,      0,      0,      0],
       [120000,      2,      2, ...,   1000,      0,   2000],
       [ 90000,      2,      2, ...,   1000,   1000,   5000],
       ...,
       [ 30000,      1,      2, ...,   4200,   2000,   3100],
       [ 80000,      1,      3, ...,   1926,  52964,   1804],
       [ 50000,      1,      2, ...,   1000,   1000,   1000]], dtype=int64)

In [6]:
Y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [7]:
X_train, X_test, y_train, y_test = train_test_split( X, Y, test_size = 0.3, random_state = 100)

In [8]:
# DECISION TREES
from sklearn.tree import DecisionTreeClassifier

In [9]:
clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100, max_depth=3, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='gini',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [10]:
clf_entropy = DecisionTreeClassifier(criterion = "entropy", random_state = 100, max_depth=3, min_samples_leaf=5)
clf_entropy.fit(X_train, y_train)

DecisionTreeClassifier(ccp_alpha=0.0, class_weight=None, criterion='entropy',
                       max_depth=3, max_features=None, max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=5, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, presort='deprecated',
                       random_state=100, splitter='best')

In [11]:
y_pred_g = clf_gini.predict(X_test)
y_pred_g

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [12]:
y_pred_e = clf_entropy.predict(X_test)
y_pred_e

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [13]:
print ("Gini accuracy is ", accuracy_score(y_test,y_pred_g)*100)

Gini accuracy is  81.83333333333334


In [14]:
print ("Entropy accuracy is ", accuracy_score(y_test,y_pred_e)*100)

Entropy accuracy is  81.83333333333334


In [15]:
# ADABOOST USING DECISION TREES

from sklearn.ensemble import AdaBoostClassifier

In [16]:
clf_ada = AdaBoostClassifier(n_estimators=50, learning_rate=1, random_state=0)

In [17]:
clf_ada.fit(X_train, y_train)

AdaBoostClassifier(algorithm='SAMME.R', base_estimator=None, learning_rate=1,
                   n_estimators=50, random_state=0)

In [18]:
y_pred_ada = clf_ada.predict(X_test)
y_pred_ada

array([0, 0, 0, ..., 0, 1, 0], dtype=int64)

In [19]:
print ("Ada boost accuracy is ", accuracy_score(y_test,y_pred_ada)*100)

Ada boost accuracy is  81.34444444444443


In [20]:
# K NEAREST NEIGHBOURS

In [21]:
from sklearn.neighbors import KNeighborsClassifier

In [22]:
for K in range(25):
 K_value = K+1
 neigh = KNeighborsClassifier(n_neighbors = K_value, weights='uniform', algorithm='auto')
 neigh.fit(X_train, y_train) 
 y_pred = neigh.predict(X_test)
 print ("Accuracy is ", accuracy_score(y_test,y_pred)*100,"% for K-Value:",K_value)

Accuracy is  68.85555555555555 % for K-Value: 1
Accuracy is  75.63333333333333 % for K-Value: 2
Accuracy is  72.93333333333332 % for K-Value: 3
Accuracy is  76.28888888888888 % for K-Value: 4
Accuracy is  74.83333333333333 % for K-Value: 5
Accuracy is  76.41111111111111 % for K-Value: 6
Accuracy is  75.66666666666667 % for K-Value: 7
Accuracy is  76.35555555555555 % for K-Value: 8
Accuracy is  75.93333333333334 % for K-Value: 9
Accuracy is  76.52222222222223 % for K-Value: 10
Accuracy is  76.1 % for K-Value: 11
Accuracy is  76.7 % for K-Value: 12
Accuracy is  76.41111111111111 % for K-Value: 13
Accuracy is  76.9 % for K-Value: 14
Accuracy is  76.78888888888889 % for K-Value: 15
Accuracy is  77.04444444444445 % for K-Value: 16
Accuracy is  76.9 % for K-Value: 17
Accuracy is  77.12222222222222 % for K-Value: 18
Accuracy is  77.08888888888889 % for K-Value: 19
Accuracy is  77.37777777777778 % for K-Value: 20
Accuracy is  77.03333333333333 % for K-Value: 21
Accuracy is  77.41111111111111 %

In [23]:
# LINEAR REGRESSION

In [24]:
from sklearn import linear_model

In [25]:
linear = linear_model.LinearRegression()
linear.fit(X_train, y_train)
linear.score(X_train, y_train)

0.12043927314357017

In [26]:
print('Coefficient: \n', linear.coef_)
print('Intercept: \n', linear.intercept_)

Coefficient: 
 [-9.68228499e-08 -1.00177263e-02 -1.25127213e-02 -2.54958721e-02
  1.27719200e-03  9.54151517e-02  1.77723832e-02  1.14866997e-02
  1.73589778e-03  3.75884030e-03  3.32072894e-03 -5.45729883e-07
  1.02945019e-07  1.02518474e-07 -1.93140800e-07 -4.97171768e-08
  1.50744521e-07 -6.64750614e-07 -2.09351729e-07  1.72891297e-07
 -1.79539023e-07 -4.77754112e-07 -3.78870438e-08]
Intercept: 
 0.306577376049386


In [27]:
y_LR = linear.predict(X_test)

In [28]:
# LOGISTIC REGRESSION
from sklearn.linear_model import LogisticRegression
LR_Model = LogisticRegression()
LR_Model.fit(X_train, y_train)
LR_Model.score(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7826666666666666

In [29]:
print('Coefficient: \n', LR_Model.coef_)
print('Intercept: \n', LR_Model.intercept_)

Coefficient: 
 [[-3.50463000e-06 -9.79250553e-04 -1.12506448e-03 -1.08121133e-03
  -1.41305118e-02  1.85553079e-03  1.41060331e-03  1.24574884e-03
   1.15788684e-03  1.07029549e-03  1.00871443e-03 -7.59685004e-06
   4.11278576e-06  3.30949708e-06 -7.58758517e-07  2.58450153e-06
   2.50717030e-06 -2.96530653e-05 -2.32090880e-05 -5.13143493e-06
  -6.74264927e-06 -7.97962875e-06 -9.59152433e-07]]
Intercept: 
 [-0.0005429]


In [29]:
y_Logistic = LR_Model.predict(X_test)

In [30]:
print ("LR accuracy is ", accuracy_score(y_test,y_Logistic)*100)

LR accuracy is  76.96666666666667


In [31]:
# SUPPORT VECTOR MACHINES

In [32]:
from sklearn.svm import SVC
SV_Model = SVC()
SV_Model.fit(X_train, y_train)
SV_Model.score(X_train, y_train)

0.783

In [33]:
y_SV = SV_Model.predict(X_test)

In [34]:
print ("SVM accuracy is ", accuracy_score(y_test,y_SV)*100)

SVM accuracy is  76.96666666666667


In [35]:
y_SV

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [36]:
# RANDOM FORESTS
from sklearn.ensemble import RandomForestClassifier
RF_Model= RandomForestClassifier()
RF_Model.fit(X_train, y_train)
RF_Model.score(X_train, y_train)

0.9995238095238095

In [37]:
y_RF = RF_Model.predict(X_test)
print ("RF accuracy is ", accuracy_score(y_test,y_RF)*100)

RF accuracy is  81.37777777777778


In [38]:
# NAIVE BAYES
from sklearn.naive_bayes import GaussianNB
NB_Model = GaussianNB()
NB_Model.fit(X_train, y_train)
NB_Model.score(X_train, y_train)

0.378

In [39]:
y_NB = NB_Model.predict(X_test)
print ("NB accuracy is ", accuracy_score(y_test,y_NB)*100)

NB accuracy is  38.733333333333334
