In [1]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

In [2]:
df = pd.read_csv('CC_Data.csv', header = 0, sep = ',')

In [3]:
df.head(10)

LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  PAY_4  \
0      20000    2          2         1   24      2      2     -1     -1   
1     120000    2          2         2   26     -1      2      0      0   
2      90000    2          2         2   34      0      0      0      0   
3      50000    2          2         1   37      0      0      0      0   
4      50000    1          2         1   57     -1      0     -1      0   
5      50000    1          1         2   37      0      0      0      0   
6     500000    1          1         2   29      0      0      0      0   
7     100000    2          2         2   23      0     -1     -1      0   
8     140000    2          3         1   28      0      0      2      0   
9      20000    1          3         2   35     -2     -2     -2     -2   

   PAY_5  ...  BILL_AMT4  BILL_AMT5  BILL_AMT6  PAY_AMT1  PAY_AMT2  PAY_AMT3  \
0     -2  ...          0          0          0         0       689         0   
1      0  ...       3272       3455       3261         0      1000      1000   
2      0  ...      14331      14948      15549      1518      1500      1000   
3      0  ...      28314      28959      29547      2000      2019      1200   
4      0  ...      20940      19146      19131      2000     36681     10000   
5      0  ...      19394      19619      20024      2500      1815       657   
6      0  ...     542653     483003     473944     55000     40000     38000   
7      0  ...        221       -159        567       380       601         0   
8      0  ...      12211      11793       3719      3329         0       432   
9     -1  ...          0      13007      13912         0         0         0   

   PAY_AMT4  PAY_AMT5  PAY_AMT6  Default  
0         0         0         0        1  
1      1000         0      2000        1  
2      1000      1000      5000        0  
3      1100      1069      1000        0  
4      9000       689       679        0  
5      1000      1000       800        0  
6     20239     13750     13770        0  
7       581      1687      1542        0  
8      1000      1000      1000        0  
9     13007      1122         0        0  

[10 rows x 24 columns]

In [4]:
Y = df.values[:, 23]
X = df.values[:, 0:23]

In [5]:
X

array([[ 20000,      2,      2, ...,      0,      0,      0],
       [120000,      2,      2, ...,   1000,      0,   2000],
       [ 90000,      2,      2, ...,   1000,   1000,   5000],
       ...,
       [ 30000,      1,      2, ...,   4200,   2000,   3100],
       [ 80000,      1,      3, ...,   1926,  52964,   1804],
       [ 50000,      1,      2, ...,   1000,   1000,   1000]], dtype=int64)

In [6]:
Y

array([1, 1, 0, ..., 1, 1, 1], dtype=int64)

In [7]:
train_test_split(X, test_size = 0.3, random_state = 100)

[array([[ 90000,      2,      3, ...,      0,    780,      0],
        [ 20000,      2,      3, ...,   1487,   3560,  15000],
        [ 20000,      1,      3, ...,      0,      0,      0],
        ...,
        [100000,      2,      2, ...,   3300,   3886,   2730],
        [ 80000,      2,      1, ...,      0,   4424,      0],
        [210000,      1,      2, ...,  17680,   2407,    497]], dtype=int64),
 array([[50000,     1,     2, ...,   665,   727,   505],
        [20000,     1,     1, ...,     0,     0,     0],
        [20000,     2,     2, ...,  5000, 10000,  8906],
        ...,
        [90000,     1,     2, ...,  1217,  1025,   500],
        [50000,     2,     2, ...,  1280,     0,     0],
        [30000,     1,     2, ...,  1443,  1949,     0]], dtype=int64)]

In [8]:
X_train, X_test = train_test_split(X, test_size = 0.3, random_state = 100)

In [9]:
X_train

array([[ 90000,      2,      3, ...,      0,    780,      0],
       [ 20000,      2,      3, ...,   1487,   3560,  15000],
       [ 20000,      1,      3, ...,      0,      0,      0],
       ...,
       [100000,      2,      2, ...,   3300,   3886,   2730],
       [ 80000,      2,      1, ...,      0,   4424,      0],
       [210000,      1,      2, ...,  17680,   2407,    497]], dtype=int64)

In [10]:
X_train.shape

(21000, 23)

In [11]:
X_test.shape

(9000, 23)

In [12]:
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.3, random_state = 100)

In [13]:
X_train.shape

(21000, 23)

In [14]:
Y_train.shape

(21000,)

In [15]:
Y_train

array([1, 0, 1, ..., 0, 0, 0], dtype=int64)

In [16]:
X_test

array([[50000,     1,     2, ...,   665,   727,   505],
       [20000,     1,     1, ...,     0,     0,     0],
       [20000,     2,     2, ...,  5000, 10000,  8906],
       ...,
       [90000,     1,     2, ...,  1217,  1025,   500],
       [50000,     2,     2, ...,  1280,     0,     0],
       [30000,     1,     2, ...,  1443,  1949,     0]], dtype=int64)

In [18]:
X_test.shape

(9000, 23)

In [19]:
Y_test.shape

(9000,)

In [20]:
from sklearn import linear_model

In [21]:
LINREG = linear_model.LinearRegression()

In [22]:
LINREG.fit(X_train, Y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
LINREG.coef_

array([-9.68228499e-08, -1.00177263e-02, -1.25127213e-02, -2.54958721e-02,
        1.27719200e-03,  9.54151517e-02,  1.77723832e-02,  1.14866997e-02,
        1.73589778e-03,  3.75884030e-03,  3.32072894e-03, -5.45729883e-07,
        1.02945019e-07,  1.02518474e-07, -1.93140800e-07, -4.97171768e-08,
        1.50744521e-07, -6.64750614e-07, -2.09351729e-07,  1.72891297e-07,
       -1.79539023e-07, -4.77754112e-07, -3.78870438e-08])

In [24]:
LINREG.intercept_

0.306577376049386

In [25]:
LINREG.score(X_train, Y_train)

0.12043927314357017

In [26]:
LINREG.score(X_test, Y_test)

0.13035644196498908

In [27]:
LOGREG = linear_model.LogisticRegression()
LOGREG.fit(X_train, Y_train)
LOGREG.score(X_train, Y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


0.7826666666666666

In [28]:
LOGREG.score(X_test, Y_test)

0.7696666666666667